spring:
  application:
    name: pcms_demo

  datasource:
    url: jdbc:postgresql://localhost:5434/pcms_demo
    username: admin_123
    password: 456_admin
    driver-class-name: org.postgresql.Driver

  jpa:
    open-in-view: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          batch_size: 25
        order_inserts: true
        order_updates: true

  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
    enabled: true

  jackson:
    serialization:
      write-dates-as-timestamps: false
    default-property-inclusion: non_null

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: alpha

logging:
  level:
    root: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
    org.springframework.web: INFO