package me.jorlowski.pcms_demo.model;

import jakarta.persistence.*;
import jakarta.validation.constraints.NotBlank;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import org.hibernate.annotations.JdbcTypeCode;
import org.hibernate.annotations.OnDelete;
import org.hibernate.annotations.OnDeleteAction;
import org.hibernate.type.SqlTypes;

import java.util.HashMap;
import java.util.Map;

/**
 * Represents a product in the catalog with dynamic specifications.
 * This entity uses PostgreSQL's JSONB capabilities to handle
 * a variable number of attributes without schema changes.
 * Each product is strictly associated with a single {@link Producer}.
 */
@Entity
@Table(name = "products")
@Getter
@Setter
@NoArgsConstructor
public class Product {

    /**
     * The unique technical identifier for the product.
     * Automatically generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * The display name of the product.
     * Must not be blank and is used for case-insensitive searches.
     */
    @NotBlank
    private String name;

    /**
     * The manufacturer of this product.
     * Uses LAZY fetching for performance and CASCADE deletion to
     * ensure data integrity when a producer is removed.
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "producer_id")
    @OnDelete(action = OnDeleteAction.CASCADE)
    private Producer producer;

    /**
     * Dynamic product specifications stored as a JSONB map.
     * Maps attribute keys to their respective values (strings, numbers, etc.).
     */
    @JdbcTypeCode(SqlTypes.JSON)
    @Column(columnDefinition = "jsonb")
    private Map<String, Object> attributes = new HashMap<>();
}