package me.jorlowski.pcms_demo.model;

import jakarta.persistence.*;
import jakarta.validation.constraints.NotBlank;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

/**
 * Represents a manufacturer or brand in the e-commerce system.
 * This entity acts as the 'one' side in the One-to-Many relationship with Products.
 * Each producer is uniquely identified by its name and can own a catalog
 * of products with varying attributes.
 */
@Entity
@Table(name = "producers")
@Getter
@Setter
@NoArgsConstructor
public class Producer {

    /**
     * The unique technical identifier for the producer.
     * Automatically generated by the database using an identity column.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * The official, unique name of the producer.
     * This field is mandatory and cannot contain only whitespace.
     */
    @Column(nullable = false, unique = true)
    @NotBlank
    private String name;
}